image: maven:4.0.0-rc-5-ibm-semeru-25-noble

stages:
  - test
  - build
  - release

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

test:
  stage: test
  script:
    - mvn test

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - mvn clean package -P server
    - mvn package -P client
  artifacts:
    paths:
      - target/server.jar
      - targer/client.jar

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Release $CI_COMMIT_TAG"
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG"
